### ISSUE TITLE
reset the config

### ISSUE THREAD

**Issue by MrCjxer** [ranenbg/Arduino-FFB-gui#10]
Hi
I want to reset the config
I mean i want see the pink window for config and change buttons again 
What should i do ?🤔

![354809695-e36e43a9-066b-4a7d-b519-fca10339342e](https://github.com/user-attachments/assets/cf7c24a2-c6ff-4b6b-8795-96febed294a2)

*Note : i didn't see this pink window never 🤔 it's just automatic did the job 😅
I am using 230cx.hex of your FW

**Comment by MrCjxer** [comment]
sorry
i'm still waiting

**Comment by ranenbg** [comment]
It's not possible to reset this config. I explained in detail in other issues you posted what you can do as a workaround, therefore I'm closing this one as it's not a GUI or firmware issue.
