### ISSUE TITLE
question about GUI app

### ISSUE THREAD

**Issue by MrCjxer** [ranenbg/Arduino-FFB-gui#12]
Hi

can I calibrate the pedal and wheel or other parameters with compiled source code?
I mean, I want to change the source code a bit and put it on the Arduino board, can I calibrate or change the parameters with the GUI software after this?
Or should I just ( Only ) use the firmwares that you have already prepared? ( fw-vXX0 or fw-vXX2 or fw-vXX3 )

**Comment by ranenbg** [comment]
Hi, this is not a question about my GUI or my firmware. Both are open source and what you do with it is your own thing - the sky is the limit.

If you make changes that break some functionality or compatibility between the two, you can't expect me to be responsible for them and provide support on fixing them. I can help with some small changes maybe, but that's it.
