### ISSUE TITLE
SimHub compatibility issue with GUI and more settings profiles

### ISSUE THREAD

**Issue by Notriatv** [ranenbg/Arduino-FFB-gui#14]
hi again XD 
1. so. while simhub is open, even in background, wheel control don't show nothing..
2. is it possible to add more than 10 profiles? bc I have 4 just for assetto corsa lol and many other games XD
3. thank you again

**Comment by ranenbg** [comment]
Hi, I think that simHub is taking over serial ports and that is why my GUI can't get acces to arduino com port. Not much I can do about that unfortunately.

Yes, I can add more profiles, these are stored in PC so there is no memory limitation. Will do it in new GUI release, tnx for suggestion.

**Comment by Notriatv** [comment]
Ah yes, that's true, you're right. The solution is simple: I just uncheck the Arduino with wheel firmware in the Arduino scan settings in SimHub, and now the GUI opens without needing to close SimHub. Thanks for the tip

![solution](https://github.com/user-attachments/assets/3a7e7d85-a050-4d1f-b501-c9d879d84e88)

**Comment by ranenbg** [comment]
Great, thank you this will be very useful for others also.

I'll close this issue as it is solved.
