### ISSUE TITLE
How to join you

### ISSUE THREAD

**Issue by arilink** [ranenbg/Arduino-FFB-gui#4]
I have some knowledge of USB HID, and I have made pedal Hub and game controller. I am very interested in force feedback steering wheel. Can I join you?

**Comment by ranenbg** [comment]
Hi dude, tnx for your interest, this project is open-source, so I'm not sure what do you mean exactly. As in joining you mean to learn something new from me? Or do you want to help me with the project? anyone can fork the code make changes and do a pull request..
