### ISSUE TITLE
License of Repo

### ISSUE THREAD

**Issue by SametBasturkk** [ranenbg/Arduino-FFB-gui#8]
Hi, I wanted to ask what is the license of repo you are planning to use?

**Comment by ranenbg** [comment]
Hi, as I wrote in the beginning of the code:

 Permission to use, copy, modify, distribute, and sell this
 software and its documentation for any purpose is hereby granted
 without fee, provided that the above copyright notice appear in
 all copies and that both that the copyright notice and this
 permission notice and warranty disclaimer appear in supporting
 documentation, and that the name of the author not be used in
 advertising or publicity pertaining to distribution of the
 software without specific, written prior permission.
 
 The author disclaim all warranties with regard to this
 software, including all implied warranties of merchantability
 and fitness.  In no event shall the author be liable for any
 special, indirect or consequential damages or any damages
 whatsoever resulting from loss of use, data or profits, whether
 in an action of contract, negligence or other tortious action,
 arising out of or in connection with the use or performance of
 this software.

So, I'm not sure what is the exact name of this license, but there it is. The same license stands for the Arduino FFB Wheel firmware. It's open-source and in principle free to use in any way as long as it's being kept open-source and available to everyone.
